[tox]
requires =
    tox>=4.2
    tox-gh-actions
env_list =
    pre-commit
    clean
    report
    build
    sphinx
    py3.1{3, 2}
skip_missing_interpreters = true
set_env =
    TEMP = {env_tmp_dir}

[testenv]
description = run the test suite
package = editable
wheel_build_env = .pkg
pass_env =
    PYTERMITE_*
set_env =
    file|env{/}.env.test
commands =
    pytest {posargs:tests}
depends =
    py3.1{3, 2}: clean
    report: py3.1{3, 2}
constraints = constraints.txt
dependency_groups = test
labels = test

[testenv:pre-commit]
description = run pre-commit hooks
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files {posargs}
labels = lint, pre-commit, ruff, mypy

[testenv:clean]
description = clean up temporary files
base_python = py3.12
skip_install = true
deps =
    coverage
commands =
    coverage erase
labels = coverage

[testenv:report]
description = generate test coverage report
base_python = py3.12
skip_install = true
deps =
    coverage
commands =
    coverage report
    coverage xml
labels = coverage

[testenv:build]
description = build source and wheel packages
base_python = py3.12
skip_install = true
commands =
    python -m build --outdir dist
dependency_groups = build
labels = build, dist

[testenv:sphinx]
description = build the Sphinx documentation
base_python = py3.12
commands =
    sphinx-build -b html docs/source docs/build/html
depends =
    pre-commit
dependency_groups = docs
labels = docs

[gh-actions]
python =
    3.12: py312
    3.13: py313
