---
defaults:
  run:
    shell: bash

name: CI
run-name: Run CI for ${{ github.ref_name }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: false
        type: string
  workflow_dispatch:

jobs:
  run-lints:
    name: Lint Code
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: ./.github/workflows/lint.yml

  run-tests:
    permissions:
      contents: read
      id-token: write
      attestations: write
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs: [run-lints, run-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate a full changelog
        uses: orhun/git-cliff-action@07dda386992489f0a6151dee53f3a137713644de
        id: git-cliff-full
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Setup Python 3.12
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.12

      - name: Format with mdformat
        run: |
          pip install mdformat mdformat-gfm
          mdformat CHANGELOG.md

      - name: Set target branch for changelog commit
        id: set-branch
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          INPUTS_VERSION: ${{ inputs.version }}
        run: |
          if [[ "${INPUTS_VERSION}" != "" ]]; then
            echo "branch=main" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Commit full changelog
        id: commit-changelog
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde
        with:
          commit_message: "chore: update changelog"
          repo: ${{ github.repository }}
          branch: ${{ steps.set-branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Generate a release changelog
        uses: orhun/git-cliff-action@07dda386992489f0a6151dee53f3a137713644de
        if: ${{ inputs.version }}
        id: git-cliff-release
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Upload changelog
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        if: ${{ inputs.version }}
        id: upload-changelog
        with:
          name: Changes
          path: CHANGES.md
          if-no-files-found: error

  dist:
    name: Build distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    needs: generate-changelog
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build and inspect the Python package
        uses: hynek/build-and-inspect-python-package@fe0a0fb1925ca263d076ca4f2c13e93a6e92a33e

  install:
    name: Check version
    runs-on: ubuntu-latest
    needs: dist
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Get artifacts from dist job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: Packages
          path: ./dist

      - name: Set up Python 3.12
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.12

      - name: Install the built package
        id: install-package
        run: |
          pip install dist/pytermite-*.whl
          version=$(python -c "import pytermite; print(pytermite.get_version())")
          echo "Installed pyTermite version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if the installed package version matches the workflow input
        if: ${{ inputs.version && inputs.version != '' }}
        id: check-version
        run: |
          if [[ "$version" != "${INPUTS_VERSION}" ]]; then
            echo "Version mismatch: Installed pyTermite has version $version
            but workflow input is ${INPUTS_VERSION}"
            exit 1
          fi
        env:
          version: ${{ steps.install-package.outputs.version }}
          INPUTS_VERSION: ${{ inputs.version }}
