---
defaults:
  run:
    shell: bash

name: Tests
run-name: Run tests for ${{ github.ref_name }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-tests
  cancel-in-progress: true

on:
  push:
    branches:
      # - main # runs via ci.yml, so we can run lint on dev only here
      - dev
  pull_request:
    branches:
      # - main # runs via ci.yml, so we can run lint on dev only here
      - dev
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test Run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.12", "3.13"]
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up .env.test file
        run: |
          mkdir -p env
          echo ${{ secrets.DOTENV_TEST }} > env/.env.test

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

      - run: uv tool install tox --with tox-uv --with tox-gh-actions

      - run: tox

      - name: Upload coverage to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' &&  matrix.python-version == '3.12'}}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
